---
title: "Food Consumption Around the World"
author: "Sean Ahn"
date: '2021 12 24 '
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)

library(tidymodels)
library(tidyverse)
```

## Explore data

```{r import_data}
food_consumption <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv")

food_consumption

```


```{r}
library(countrycode)

food <- 
  food_consumption %>% 
  mutate(continent = countrycode(country, 
                                 origin = "country.name",
                                 destination = "continent")) %>% 
  select(-co2_emmission) %>% 
  pivot_wider(names_from = food_category,
              values_from = consumption) %>% 
  janitor::clean_names() %>% 
  mutate(asia = case_when(continent == "Asia" ~ "Asia",
                          TRUE ~ "Other")) %>% 
  select(-country, -continent) %>% 
  mutate_if(is.character, factor)

```


```{r}
library(GGally)


# ggsactmat() 함수를 쓸 때는 들어가는 모든 데이터가 numeric이어야 함!
ggscatmat(food, columns = 1:11, color = "asia", alpha = 0.6)

```


## Tune hyperparameters


```{r}
set.seed(1234)

food_boot <- bootstraps(food, times = 30)

# mtry: predictor를 몇 개나 randomly sample 할 것인지?
rf_spec <- 
  rand_forest(mode = "classification",
              mtry = tune(),
              trees = 1000,
              min_n = tune()) %>% 
  set_engine("ranger")

rf_rec <- 
  recipe(asia ~ ., data = food)

rf_wf <- 
  workflow() %>% 
  add_model(rf_spec) %>% 
  add_recipe(rf_rec)

rf_grid <- 
  rf_wf %>% 
  tune_grid(
  resamples = food_boot
)



```

```{r}
rf_grid %>% 
  collect_metrics()


rf_grid %>% 
  show_best("roc_auc")

```

