---
title: "store_sales"
author: "J.H AHN"
date: '2021 12 14 '
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
gc()

library(tidymodels)
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(fabletools)
library(lubridate)
library(timetk)

knitr::opts_chunk$set(echo = TRUE)
```

## Import data

```{r Import}
raw_test <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/test.csv")
raw_train <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/train.csv")
raw_oil <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/oil.csv")
raw_holiday <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/holidays_events.csv")
raw_store <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/stores.csv")
raw_transactions <- read_csv("D:/R_DATA/store-sales-time-series-forecasting/transactions.csv")

```


## binding raw files

```{r bind_train_test_csv}
raw_test$set <- "test"
raw_train$set <- "train"

raw_full <- 
  bind_rows(raw_test, raw_train)

# c(nrow(raw_train), nrow(raw_test), nrow(raw_full))

```


## recode family


```{r}
raw_full$family <- 
  raw_full$family %>% recode(
    AUTOMOTIVE = 'AUTO',                 
    `BABY CARE` = 'BABY',                
    BEVERAGES = 'BEVER',                 
    `BREAD/BAKERY` = 'BREAD',             
    CELEBRATION = 'CELEB',               
    CLEANING = 'CLEAN',                 
    `FROZEN FOODS`= 'FOOD',           
    `GROCERY I` = 'GROC1',                 
    `GROCERY II` = 'GROC2',                
    HARDWARE = 'HW',                 
    `HOME AND KITCHEN I` = 'HOME1',         
    `HOME AND KITCHEN II` = 'HOME2',       
    `HOME APPLIANCES` = 'APPLI',          
    `HOME CARE` = 'CARE',                  
    LADIESWEAR = 'LADIES',                
    `LAWN AND GARDEN` = 'GARDEN',           
    LINGERIE = 'LINGER',                   
    `LIQUOR,WINE,BEER` = 'LIQR',           
    MAGAZINES = 'MAGAZ',                
    `PERSONAL CARE` = 'PERCA',              
    `PET SUPPLIES` = 'PET',              
    `PLAYERS AND ELECTRONICS` = 'ELECT',   
    POULTRY  = 'POULT',                  
    `PREPARED FOODS` = 'PREFD',            
    `SCHOOL AND OFFICE SUPPLIES` = 'SCHOOL'
  )


```


## Merge data


```{r merge_earth_quake}
raw_full$earthquake <-
  if_else(raw_full$date >= as.Date("2014-08-12") &
            raw_full$date <= as.Date("2014-08-16"), 1, 0)

```




```{r merge_holiday}
simple_holiday <- 
  raw_holiday %>% 
  select(date, type, transferred)

nrow(simple_holiday) # for checking, delete later

# removed duplicated rows
simple_holiday <- 
  simple_holiday %>% distinct(date, .keep_all = TRUE)

nrow(simple_holiday) # for checking, delete later

simple_holiday <- simple_holiday %>% 
  filter_by_time(.date_var = date,
                 .start_date = min(raw_full$date), 
                 .end_date = max(raw_full$date)) %>% 
  mutate(working = case_when(type == "Holiday"&transferred == "FALSE" ~ 0,
                             type %in% c("Transfer", "Additional","Event") ~ 0,
                             TRUE ~ 1)
  )


raw_full <-
  raw_full %>%
  left_join(simple_holiday, by = 'date')


raw_full$working <- if_else(is.na(raw_full$working), 0, raw_full$working)


raw_full <- raw_full %>% select(-c(type, transferred))

```



## Merge oil_price


```{r}
oil_tsbl <- as_tsibble(raw_oil, index = date, regular = TRUE)

fit_oilprice <- 
  oil_tsbl %>% 
  fill_gaps(.full = TRUE) %>%
  model(randomwalk = RW(dcoilwtico ~ drift()))


fitted_oil <- 
  fit_oilprice %>% 
  augment() %>% 
  filter(.model == "randomwalk") %>% 
  select(c(date, dcoilwtico, .fitted))


fitted_oil <- 
  fitted_oil %>% 
  mutate(dcoilwtico = case_when(is.na(dcoilwtico) ~ .fitted,
                                TRUE ~ fitted_oil$dcoilwtico))

fitted_oil$dcoilwtico[1] <- fitted_oil$dcoilwtico[2]

fitted_oil <- 
  fitted_oil %>% 
  rename(oil_price = dcoilwtico) %>% 
  select(-.fitted)

raw_full <- 
  raw_full %>% 
  left_join(fitted_oil, by = 'date')



```



## merge transaction


```{r merge_transaction}

raw_trs <- 
  raw_transactions %>% 
  left_join(raw_store, by = 'store_nbr')

tsbl_trs <- 
  raw_trs %>% 
  select(date, transactions, store_nbr, state, city) %>% 
  as_tsibble(index = date, key = c(store_nbr, state, city))


tsbl_trs <- 
  tsbl_trs %>% fill_gaps()

tsbl_trs$transactions <- 
  if_else(is.na(tsbl_trs$transactions), 0, tsbl_trs$transactions)


fit_trs <- 
  tsbl_trs %>% 
  model(base = ETS(transactions))

# estimate daily transaction using ETS
fcast_trs <- 
  fit_trs %>% 
  forecast(h = "15 days")

fitted_trs <- 
  as.data.frame(fcast_trs) %>% 
  select(-c(.model, transactions)) %>% 
  rename(transactions = .mean)

raw_full <- 
  raw_full %>% 
  left_join(raw_store %>% select('store_nbr', 'city', 'state'),
            by = 'store_nbr')

hist_trs <- 
  raw_trs %>% tibble() %>% 
  select(-c(type, cluster))

full_trs <- 
  bind_rows(hist_trs, fitted_trs)

raw_full <- 
  raw_full %>% 
  left_join(full_trs, by = c('date', 'store_nbr', 'city', 'state')) %>% 
  select(-ends_with('.x'))

raw_full$transactions <-
  if_else(is.na(raw_full$transactions), 0, raw_full$transactions)

```


```{r}
full_trs %>% filter(date > as.Date("2017-08-01"), store_nbr < 10) %>% 
  ggplot(aes(date, transactions, color = as.factor(store_nbr))) + geom_line() +
  facet_wrap(~ store_nbr, scales = "free_y", ncol = 3)


```



### change column properties

```{r change_column_properties}
raw_full <- 
  raw_full %>% select(-c(city, state))

raw_full$store_nbr <- as.factor(raw_full$store_nbr)
raw_full$family <- as.factor(raw_full$family)
raw_full$earthquake <- as.factor(raw_full$earthquake)
raw_full$working <- as.factor(raw_full$working)

```



### decompose date


```{r decompose_date}
raw_full$year <- year(raw_full$date)
raw_full$month <- month(raw_full$date)
raw_full$day <- day(raw_full$date)
raw_full$wday <- wday(raw_full$date)
raw_full$week <- week(raw_full$date)

```



### generate lag column

```{r generate_lag_column}
# raw_full <- 
#   raw_full %>% group_by(store_nbr, family) %>% 
#   mutate(lag1 = dplyr::lag(sales, n=1, default = NA)) %>% 
#   ungroup()
# 
# raw_full <- 
#   raw_full %>% group_by(store_nbr, family) %>% 
#   mutate(lag7 = dplyr::lag(sales, n=7, default = NA)) %>% 
#   ungroup()
# 
# raw_full <- 
#   raw_full %>% group_by(store_nbr, family) %>% 
#   mutate(lag14 = dplyr::lag(sales, n=14, default = NA)) %>% 
#   ungroup()

```



### generate ratio column


```{r generate_ratio_column}
raw_full <- 
  raw_full %>% group_by(date, store_nbr) %>%
  mutate(daily_sales = sum(sales)) %>% 
  ungroup() %>% 
  mutate(ratio_sales = case_when(daily_sales > 0  ~ round(sales / daily_sales, 5),
                                 TRUE ~ 0))

raw_full$daily_transactions <- raw_full$transactions

raw_full <- 
  raw_full %>% 
  mutate(transactions = case_when(daily_transactions > 0 ~ round(daily_transactions * ratio_sales,3),
                                  TRUE ~ 0))

```




```{r}
df <- raw_full %>% 
  group_by(store_nbr)

df_set <- df %>% group_split()

```


```{r}
df_train <- df_set[[5]] %>% filter(set == "train")
df_test <- df_set[[5]] %>% filter(set == "test")

df_split <- initial_split(df_train)
df_analysis <- training(df_split)
df_assess <- testing(df_split)

set.seed(123)
df_folds <- vfold_cv(df_analysis, v = 5)


```


```{r}
rf_spec <- 
  rand_forest(mtry = tune(), trees = 1000, min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")


```


```{r}
rf_rec <- 
  recipe(sales ~ ., data = df_analysis) %>% 
  update_role(c(id, store_nbr, family, set, daily_sales, 
                ratio_sales, daily_transactions), 
              new_role = "id") %>% 
  step_impute_knn(transactions, 
                  impute_with = imp_vars(c(store_nbr, family, onpromotion, earthquake, oil_price,
                                           year, month, day, wday, week))) %>% 
  # step_lag(sales, lag = c(1,7,14), default = 0) %>% 
  step_dummy(all_nominal_predictors())

```


```{r}
rf_wf <- 
  workflow() %>% 
  add_model(rf_spec) %>% 
  add_recipe(rf_rec)


```


```{r}
library(finetune)

rf_res <- 
  rf_wf %>% 
  tune_race_anova(
    resamples = df_folds,
    grid = 25,
    control = control_race(verbose = TRUE)
  )


# rf_res <- 
#   rf_wf %>% 
#   tune_grid(
#     resample = df_folds,
#     grid = 5,
#     control = control_grid(verbose = TRUE, save_pred = TRUE)
#   )

```

```{r}
final_wf <- 
  rf_wf %>% 
  finalize_workflow(select_best(rf_res, metric = "rmse"))

```

```{r}
rf_fit <-
  final_wf %>% 
  last_fit(df_split)

final_fit <- 
  fit(rf_fit$.workflow[[1]], df_train)

```

```{r}
submit <- 
  predict(final_fit, new_data = df_test) %>% 
  bind_cols(df_test$id)

names(submit) <- c("sales", "id")

submit <- 
  submit %>% select(id, everything())

```

